; ─────────────────────────────────────────────────────────
;  AllStar HTTP node registrations
;  Per-user registrations are dynamically included from
;  /etc/asterisk/users/users_reg.conf, written by the API.
; ─────────────────────────────────────────────────────────

[general]

[registrations]
#tryinclude /etc/asterisk/users/users_reg.conf
